### DISCUSSION TITLE
Responsive tokens

### DISCUSSION THREAD

**Discussion by shashkovdanil** [stitchesjs/stitches#284] [Ideas] [answered]
I think it's good idea!

```js
export const { styled, css } = createStyled({
  tokens: {
    fontSizes: {
      $base: '16px',
      large: {
        $base: '20px', // It's useful for responsive text (if you use rem)
      },
    },
    space: {
      $pagePadding: '16px',
      large: {
        $pagePadding: '80px',
      },
    },
  },
  breakpoints: {
    large: (rule) => `@media (min-width: 2200px) { ${rule} }`,
  },
});
```

In css

```css
:root {
  --fontSizes-base: 16px;
}

@media (min-width: 2200px) {
  :root {
     --fontSizes-base: 20px;
  }
}

html {
  font-size: var(--fontSizes-base);
}

p {
  font-size: 1rem;
}
```
