### DISCUSSION TITLE
Plain export JSS to simple CSS classes

### DISCUSSION THREAD

**Discussion by cudr** [stitchesjs/stitches#787] [Ideas]
**Is your feature request related to a problem? Please describe.**
Hey! Thanks for this awesome library, this is a question or feature request.

**Describe the solution you'd like**
Is there a way to export plain css with simple class names?

For example, convert this:

```js
const theme = {
    colors: {
        red: 'red',
        green: 'green',
        brown: 'brown'
    },
    sizes: {
        l: '40px',
        m: '32px',
        s: '24px'
    }
}

const button = {
    color: '$red',
    variants: {
        variant: {
            primary: {
                color: '$green'
            },
            secondary: {
                color: '$brown'
            }
        },
        size: {
            l: {
                height: '$sizes$l'
            },
            m: {
                height: '$sizes$m'
            },
            s: {
                height: '$sizes$s'
            }
        }
    }
}
```
to css like:
```css
:root {
  --colors-red: red;
  --colors-green: green;
  --colors-brown: brown;

  --sizes-l: 40px;
  --sizes-m: 32px;
  --sizes-s: 24px;
}

:root {
  --button-color: var(--colors-red);
  --button-variant-primary-color: var(--colors-green);
  --button-variant-secondary-color: var(--colors-brown);

  --button-size-l-height: var(--sizes-l);
  --button-size-m-height: var(--sizes-m);
  --button-size-s-height: var(--sizes-s);
}

.button {
  color: var(--button-color);
}
.button-variant-primary {
  color: var(--button-variant-primary-color);
}
.button-variant-secondary {
  color: var(--button-variant-secondary-color);
}
.button-size-l {
  height: var(--button-size-l-height);
}
.button-size-m {
  height: var(--button-size-m-height);
}
.button-size-m {
  height: var(--button-size-m-height);
}
```

I think this should be implemented by some stage of preparing the theme -> and converting by ```@stitches/stringify``` to css.

**Additional context**
Strongly agree with https://github.com/modulz/stitches/pull/477 motivation, it will be an killer feature.
