### DISCUSSION TITLE
P3 Color Support

### DISCUSSION THREAD

**Discussion by derekr** [stitchesjs/stitches#823] [Help] [answered]
Doing some early exploration of enabling display-p3 color. A preferable approach is setting custom properties based on a supports rule.

_https://webkit.org/blog/10042/wide-gamut-color-in-css-with-display-p3/_ 
```css
/* sRGB color. */
:root {
    --bright-green: rgb(0, 255, 0);
}

/* Display-P3 color, when supported. */
@supports (color: color(display-p3 1 1 1)) {
    :root {
        --bright-green: color(display-p3 0 1 0);
    }
}

header {
    color: var(--bright-green);
}
```

So wondering if there's a way of using globalCss to achieve something similar either through local scopes or some how toggling between multiple themes (base theme and display-p3 theme).

```js
const globalStyles = stitchesConfig.globalCss({
	'@supports (color: color(display-p3 1 1 1))': {
		':root': {
			???
		}
	}
})

// or

const displayP3Theme = stitchesConfig.createTheme('dispaly-p3', {
	'$red': 'color(display-p3 0 1 0)'
})

// check for support and swap theme
```
